# Generated by Django 2.2.12 on 2020-04-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
