# Generated by Django 2.2.12 on 2020-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_delete_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='base_cost',
            field=models.FloatField(default=0),
        ),
    ]
