# Generated by Django 2.2.12 on 2020-04-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('bofa1', models.FloatField(default=0)),
                ('bofa2', models.FloatField(default=0)),
                ('pnc', models.FloatField(default=0)),
                ('dcu', models.FloatField(default=0)),
                ('fidelity', models.FloatField(default=0)),
                ('coastal', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
